POST http://localhost:3333/classes
Content-Type: application/json

{
    "name": "Antonio",
    "avatar": "https://avatars1.githubusercontent.com/u/35160032?s=460&u=c2fd8dd4d7356247dafc16dc5ac823721b7bc9bd&v=4",
    "whatsapp": "+556892065657",
    "bio": "Desenvolvedor Web com 4 anos de mercado",
    "subject": "Redação",
    "cost": 100,
    "schedule": [
        {"week_day": 3, "from": "10:00", "to": "18:00"},
        {"week_day": 4, "from": "8:00", "to": "15:00"}
    ]
}

###
GET http://localhost:3333/classes?week_day=1&subject=Matemática&time=8:00